export const images = {
  icon: require("../assets/images/icon.png"),
  logo: require("../assets/images/logo.png"),
  mamaIntro: require("../assets/images/mamaIntro.png"),
  slide3: require("../assets/images/slide3.png"),
  slide4: require("../assets/images/slide4.png"),
  slide5: require("../assets/images/slide5.png"),
  slide6: require("../assets/images/slide6.png"),
  splashIcon: require("../assets/images/splash-icon.png"),
  slide2: require("../assets/images/slide2.png"),
  mom: require("../assets/images/mom.webp"),
  baby: require("../assets/images/baby.webp"),
  google: require("../assets/images/google.webp"),
  apple: require("../assets/images/apple.png"),
  mascot: require("../assets/images/mascot.png"),
  mascotCry: require("../assets/images/mascotCry.png"),
};
