export const images = {
  icon: require("../assets/images/icon.png"),
  logo: require("../assets/images/logo2.png"),
  mamaIntro: require("../assets/images/mamaIntro.webp"),
  slide3: require("../assets/images/slide3.webp"),
  slide4: require("../assets/images/slide4.webp"),
  slide5: require("../assets/images/slide5.webp"),
  slide6: require("../assets/images/slide6.webp"),
  splashIcon: require("../assets/images/cover.png"),
  slide2: require("../assets/images/slide2.webp"),
  mom: require("../assets/images/mom.webp"),
  baby: require("../assets/images/baby.webp"),
  google: require("../assets/images/google.webp"),
  apple: require("../assets/images/apple.png"),
  mascot: require("../assets/images/mascot.webp"),
  mascotLoved: require("../assets/images/mascotLoved.webp"),
  mascotCeleb: require("../assets/images/mascotCeleb.webp"),
  mascotWaving: require("../assets/images/mascotWaving.webp"),
  mascotSleep: require("../assets/images/mascotSleep.webp"),
  mascotDoctor: require("../assets/images/mascotDoctor.webp"),
  mascotSearch: require("../assets/images/mascotSearch.webp"),
  mascotCry: require("../assets/images/mascotCry.webp"),
};
